# Generated by Django 5.0.1 on 2026-01-16 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Archivo')),
                ('file_type', models.CharField(max_length=10, verbose_name='Tipo de archivo')),
                ('file_size', models.IntegerField(verbose_name='Tamaño (bytes)')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Autor')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('doi', models.CharField(blank=True, max_length=255, verbose_name='DOI')),
                ('abstract', models.TextField(blank=True, verbose_name='Resumen')),
                ('keywords', models.TextField(blank=True, verbose_name='Palabras clave')),
                ('total_pages', models.IntegerField(blank=True, null=True, verbose_name='Total de páginas')),
                ('total_chunks', models.IntegerField(default=0, verbose_name='Total de chunks')),
                ('indexed_in_faiss', models.BooleanField(default=False, verbose_name='Indexado en FAISS')),
                ('indexed_in_neo4j', models.BooleanField(default=False, verbose_name='Indexado en Neo4j')),
                ('faiss_index_path', models.CharField(blank=True, max_length=500, verbose_name='Ruta índice FAISS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de procesamiento')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.CharField(max_length=255, unique=True, verbose_name='ID del chunk')),
                ('text', models.TextField(verbose_name='Texto')),
                ('chunk_index', models.IntegerField(verbose_name='Índice del chunk')),
                ('page_number', models.IntegerField(blank=True, null=True, verbose_name='Número de página')),
                ('section', models.CharField(blank=True, max_length=100, verbose_name='Sección')),
                ('embedding_preview', models.TextField(blank=True, verbose_name='Preview del embedding')),
                ('similarity_score', models.FloatField(blank=True, null=True, verbose_name='Score de similitud (última búsqueda)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Chunk de documento',
                'verbose_name_plural': 'Chunks de documentos',
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-created_at'], name='documents_d_created_71dced_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', '-created_at'], name='documents_d_user_id_a8f8c0_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_d_status_07369e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='documents_d_documen_8ea6ce_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['chunk_id'], name='documents_d_chunk_i_9a08ac_idx'),
        ),
    ]
